services:
  - type: web
    name: sigs-ti-pronet
    runtime: node
    buildCommand: pnpm run build:render
    startCommand: pnpm run start:render
    preDeployCommand: pnpm run seed:render
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
